### ISSUE TITLE
Publicar a versão v1.0

### ISSUE THREAD

**Issue by edupferraz** [Lorum-Gaming/God-Between-Us#56]
O jogo deve preencher os seguintes requisitos:

- [ ] Suporte a toque de tela #27 
- [ ] Tela cheia #32 
- [ ] Salas de partida #38 
- [ ] Multijogador #39 
- [ ] Publicação de conteúdo estático #46 
- [ ] Publicação de conteúdo dinâmico #47 
- [ ] Áudio sobre WebRTC #52 
- [ ] Validação em teste alfa #52 
- [ ] PWA #55
